//go:build ignore

// Writes version.go: the forskap-api version the binding is generated from,
// read from the crate's manifest. Run by `go generate` (see gen.go).
package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"regexp"
	"strings"
)

const manifest = "../../forskap-api/Cargo.toml"

var versionLine = regexp.MustCompile(`^version\s*=\s*"([^"]+)"\s*$`)

func main() {
	version, err := packageVersion(manifest)
	if err != nil {
		log.Fatalf("genversion: %v", err)
	}
	out := fmt.Sprintf(`// Code generated by genversion.go from forskap-api/Cargo.toml; DO NOT EDIT.

package orgthehosterforskapd

// APIVersion is the version of the org.thehoster.forskapd interface this
// binding was generated from: the forskap-api crate's. Compare a daemon's with
// Status.Compatible.
const APIVersion = %q
`, version)
	if err := os.WriteFile("version.go", []byte(out), 0o644); err != nil {
		log.Fatalf("genversion: %v", err)
	}
}

// packageVersion is the literal version of the manifest's [package] section.
func packageVersion(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	section := ""
	lines := bufio.NewScanner(f)
	for lines.Scan() {
		line := strings.TrimSpace(lines.Text())
		if strings.HasPrefix(line, "[") {
			section = line
			continue
		}
		if section != "[package]" {
			continue
		}
		if m := versionLine.FindStringSubmatch(line); m != nil {
			return m[1], nil
		}
	}
	if err := lines.Err(); err != nil {
		return "", err
	}
	return "", fmt.Errorf("%s: no literal version in [package]", path)
}
