// Code generated by github.com/varlink/go/cmd/varlink-go-interface-generator, DO NOT EDIT.

package orgthehosterforskapd

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/varlink/go/varlink"
)

// Generated type declarations

// A work item named by where it lives and its number.
type WorkItemRef struct {
	Project_id *int64  `json:"project_id,omitempty"`
	Group_id   *int64  `json:"group_id,omitempty"`
	Iid        int64   `json:"iid"`
	Type       *string `json:"type,omitempty"`
	Title      *string `json:"title,omitempty"`
	Web_url    *string `json:"web_url,omitempty"`
}

// An issue, task, epic, …: GitLab's work item, of a project or of a group.
type WorkItem struct {
	Id             int64        `json:"id"`
	Iid            int64        `json:"iid"`
	Type           string       `json:"type"`
	Project_id     *int64       `json:"project_id,omitempty"`
	Group_id       *int64       `json:"group_id,omitempty"`
	Namespace_path *string      `json:"namespace_path,omitempty"`
	Title          string       `json:"title"`
	Web_url        string       `json:"web_url"`
	State          string       `json:"state"`
	Parent         *WorkItemRef `json:"parent,omitempty"`
	Time_spent     *int64       `json:"time_spent,omitempty"`
	Board_column   *string      `json:"board_column,omitempty"`
	Open_count     int64        `json:"open_count"`
	Project_avatar *string      `json:"project_avatar,omitempty"`
	Updated_at     *int64       `json:"updated_at,omitempty"`
}

// What a write or RecordOpen targets; an issue is a work_item.
type IssuableKind string

// Where a HistoryEvent comes from.
type HistorySource string

// Time logged on an issue or merge request.
type HistoryEvent struct {
	Timestamp  int64         `json:"timestamp"`
	Source     HistorySource `json:"source"`
	Kind       IssuableKind  `json:"kind"`
	Project_id int64         `json:"project_id"`
	Iid        int64         `json:"iid"`
	Title      *string       `json:"title,omitempty"`
	Web_url    *string       `json:"web_url,omitempty"`
	Time_spent *int64        `json:"time_spent,omitempty"`
	Duration   *string       `json:"duration,omitempty"`
	Summary    *string       `json:"summary,omitempty"`
}

// One of the user's contribution events (GitLab's GET /events).
type ActivityEvent struct {
	Timestamp    int64   `json:"timestamp"`
	Action       string  `json:"action"`
	Target_type  *string `json:"target_type,omitempty"`
	Target_iid   *int64  `json:"target_iid,omitempty"`
	Target_title *string `json:"target_title,omitempty"`
	Project_id   *int64  `json:"project_id,omitempty"`
	Project_path *string `json:"project_path,omitempty"`
	Web_url      *string `json:"web_url,omitempty"`
	Ref          *string `json:"ref,omitempty"`
	Commit_count *int64  `json:"commit_count,omitempty"`
	Commit_title *string `json:"commit_title,omitempty"`
	Description  *string `json:"description,omitempty"`
}

// A write that exhausted its retry window or was rejected while draining.
type FailedTask struct {
	Id         int64        `json:"id"`
	Op         string       `json:"op"`
	Kind       IssuableKind `json:"kind"`
	Project_id int64        `json:"project_id"`
	Iid        int64        `json:"iid"`
	Detail     string       `json:"detail"`
	Error      string       `json:"error"`
	Queued_at  int64        `json:"queued_at"`
	Failed_at  int64        `json:"failed_at"`
}

type MergeRequest struct {
	Id             int64    `json:"id"`
	Iid            int64    `json:"iid"`
	Project_id     int64    `json:"project_id"`
	Title          string   `json:"title"`
	Web_url        string   `json:"web_url"`
	State          string   `json:"state"`
	Assignees      []string `json:"assignees"`
	Open_count     int64    `json:"open_count"`
	Project_avatar *string  `json:"project_avatar,omitempty"`
	Project_path   *string  `json:"project_path,omitempty"`
	Updated_at     *int64   `json:"updated_at,omitempty"`
}

// A project the user is a member of.
type Project struct {
	Id        int64   `json:"id"`
	Name      string  `json:"name"`
	Full_path string  `json:"full_path"`
	Web_url   string  `json:"web_url"`
	Avatar    *string `json:"avatar,omitempty"`
	Archived  bool    `json:"archived"`
}

// A group the user is a member of.
type Group struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	Full_path string `json:"full_path"`
	Web_url   string `json:"web_url"`
}

// Why the daemon has no GitLab session.
type NotAuthReason string

// The projects and groups a call keeps to: an item passes if it lies in any of
// them. Nothing listed is no filter.
type Scope struct {
	Projects *[]int64  `json:"projects,omitempty"`
	Groups   *[]string `json:"groups,omitempty"`
}

// Which of ListWorkItems' lists: the issues the user authored, or is assigned to.
type WorkItemRole string

// The states ListWorkItems filters by; WorkItem.state carries them.
type WorkItemState string

// Which of the user's own issues ListWorkItems lists; nothing set is all of
// them.
type WorkItemFilter struct {
	Role          *WorkItemRole    `json:"role,omitempty"`
	Updated_after *int64           `json:"updated_after,omitempty"`
	States        *[]WorkItemState `json:"states,omitempty"`
}

// The result sets of a Search.
type SearchKind string

// How a Search narrows its results; nothing set narrows nothing.
type SearchOptions struct {
	Kinds         *[]SearchKind `json:"kinds,omitempty"`
	Limit         *int64        `json:"limit,omitempty"`
	Scope         *Scope        `json:"scope,omitempty"`
	Types         *[]string     `json:"types,omitempty"`
	Exclude_types *[]string     `json:"exclude_types,omitempty"`
	Match_all     *bool         `json:"match_all,omitempty"`
}

// The issue CreateWorkItem files.
type NewWorkItem struct {
	Title       string       `json:"title"`
	Description *string      `json:"description,omitempty"`
	Labels      *[]string    `json:"labels,omitempty"`
	Assign_self *bool        `json:"assign_self,omitempty"`
	Parent      *WorkItemRef `json:"parent,omitempty"`
}

// The call fits the interface, but an argument's value is not acceptable (a
// number that isn't positive, a malformed duration, a blank title, …): nothing
// was sent to GitLab or stored. argument names it, a nested value by its path
// ("project_id", "iid", "duration", "options.limit", "item.title", …).
type InvalidArgument struct {
	Argument string `json:"argument"`
	Message  string `json:"message"`
}

func (e InvalidArgument) Error() string {
	s := "org.thehoster.forskapd.InvalidArgument"
	s += fmt.Sprintf("(Argument: %v, Message: %v)", e.Argument, e.Message)
	return s
}

// The daemon has no such thing: a failure id RetryFailure or DismissFailure
// doesn't know.
type NotFound struct {
	Message string `json:"message"`
}

func (e NotFound) Error() string {
	s := "org.thehoster.forskapd.NotFound"
	s += fmt.Sprintf("(Message: %v)", e.Message)
	return s
}

// GitLab answered and refused the request.
type GitlabError struct {
	Message string `json:"message"`
	Status  *int64 `json:"status,omitempty"`
}

func (e GitlabError) Error() string {
	s := "org.thehoster.forskapd.GitlabError"
	s += fmt.Sprintf("(Message: %v, Status: %v)", e.Message, e.Status)
	return s
}

// GitLab could not be reached, or answered 429 or 5xx, and the daemon did not
// queue the call: whether GitLab carried it out is unknown.
type GitlabUnavailable struct {
	Message string `json:"message"`
}

func (e GitlabUnavailable) Error() string {
	s := "org.thehoster.forskapd.GitlabUnavailable"
	s += fmt.Sprintf("(Message: %v)", e.Message)
	return s
}

// The daemon could not do it for a reason of its own, its storage failing.
type Internal struct {
	Message string `json:"message"`
}

func (e Internal) Error() string {
	s := "org.thehoster.forskapd.Internal"
	s += fmt.Sprintf("(Message: %v)", e.Message)
	return s
}

// The daemon has no live GitLab session; detail carries the host and the
// underlying error for the reasons that have one.
type NotAuthenticated struct {
	Reason *NotAuthReason `json:"reason,omitempty"`
	Detail *string        `json:"detail,omitempty"`
}

func (e NotAuthenticated) Error() string {
	s := "org.thehoster.forskapd.NotAuthenticated"
	s += fmt.Sprintf("(Reason: %v, Detail: %v)", e.Reason, e.Detail)
	return s
}

func Dispatch_Error(err error) error {
	if e, ok := err.(*varlink.Error); ok {
		switch e.Name {
		case "org.thehoster.forskapd.InvalidArgument":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param InvalidArgument
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		case "org.thehoster.forskapd.NotFound":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param NotFound
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		case "org.thehoster.forskapd.GitlabError":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param GitlabError
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		case "org.thehoster.forskapd.GitlabUnavailable":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param GitlabUnavailable
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		case "org.thehoster.forskapd.Internal":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param Internal
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		case "org.thehoster.forskapd.NotAuthenticated":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param NotAuthenticated
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		}
	}
	return err
}

// Generated client method calls

// Open issues assigned to the user, optionally only those in the scope.
type GetAssignedWorkItems_methods struct{}

func GetAssignedWorkItems() GetAssignedWorkItems_methods { return GetAssignedWorkItems_methods{} }

func (m GetAssignedWorkItems_methods) Call(ctx context.Context, c *varlink.Connection, scope_in_ *Scope) (work_items_out_ []WorkItem, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, scope_in_)
	if err_ != nil {
		return
	}
	work_items_out_, _, err_ = receive(ctx)
	return
}

func (m GetAssignedWorkItems_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, scope_in_ *Scope) (func(ctx context.Context) ([]WorkItem, uint64, error), error) {
	var in struct {
		Scope *Scope `json:"scope,omitempty"`
	}
	in.Scope = scope_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.GetAssignedWorkItems", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (work_items_out_ []WorkItem, flags uint64, err error) {
		var out struct {
			Work_items []WorkItem `json:"work_items"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		work_items_out_ = []WorkItem(out.Work_items)
		return
	}, nil
}

func (m GetAssignedWorkItems_methods) Upgrade(ctx context.Context, c *varlink.Connection, scope_in_ *Scope) (func(ctx context.Context) (work_items_out_ []WorkItem, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Scope *Scope `json:"scope,omitempty"`
	}
	in.Scope = scope_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.GetAssignedWorkItems", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (work_items_out_ []WorkItem, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Work_items []WorkItem `json:"work_items"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		work_items_out_ = []WorkItem(out.Work_items)
		return
	}, nil
}

// Open merge requests assigned to the user, optionally only those in the scope.
type GetAssignedMergeRequests_methods struct{}

func GetAssignedMergeRequests() GetAssignedMergeRequests_methods {
	return GetAssignedMergeRequests_methods{}
}

func (m GetAssignedMergeRequests_methods) Call(ctx context.Context, c *varlink.Connection, scope_in_ *Scope) (merge_requests_out_ []MergeRequest, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, scope_in_)
	if err_ != nil {
		return
	}
	merge_requests_out_, _, err_ = receive(ctx)
	return
}

func (m GetAssignedMergeRequests_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, scope_in_ *Scope) (func(ctx context.Context) ([]MergeRequest, uint64, error), error) {
	var in struct {
		Scope *Scope `json:"scope,omitempty"`
	}
	in.Scope = scope_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.GetAssignedMergeRequests", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (merge_requests_out_ []MergeRequest, flags uint64, err error) {
		var out struct {
			Merge_requests []MergeRequest `json:"merge_requests"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		merge_requests_out_ = []MergeRequest(out.Merge_requests)
		return
	}, nil
}

func (m GetAssignedMergeRequests_methods) Upgrade(ctx context.Context, c *varlink.Connection, scope_in_ *Scope) (func(ctx context.Context) (merge_requests_out_ []MergeRequest, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Scope *Scope `json:"scope,omitempty"`
	}
	in.Scope = scope_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.GetAssignedMergeRequests", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (merge_requests_out_ []MergeRequest, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Merge_requests []MergeRequest `json:"merge_requests"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		merge_requests_out_ = []MergeRequest(out.Merge_requests)
		return
	}, nil
}

// The user's own issues, closed ones included, updated recently; newest-updated
// first.
type ListWorkItems_methods struct{}

func ListWorkItems() ListWorkItems_methods { return ListWorkItems_methods{} }

func (m ListWorkItems_methods) Call(ctx context.Context, c *varlink.Connection, filter_in_ *WorkItemFilter) (work_items_out_ []WorkItem, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, filter_in_)
	if err_ != nil {
		return
	}
	work_items_out_, _, err_ = receive(ctx)
	return
}

func (m ListWorkItems_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, filter_in_ *WorkItemFilter) (func(ctx context.Context) ([]WorkItem, uint64, error), error) {
	var in struct {
		Filter *WorkItemFilter `json:"filter,omitempty"`
	}
	in.Filter = filter_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.ListWorkItems", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (work_items_out_ []WorkItem, flags uint64, err error) {
		var out struct {
			Work_items []WorkItem `json:"work_items"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		work_items_out_ = []WorkItem(out.Work_items)
		return
	}, nil
}

func (m ListWorkItems_methods) Upgrade(ctx context.Context, c *varlink.Connection, filter_in_ *WorkItemFilter) (func(ctx context.Context) (work_items_out_ []WorkItem, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Filter *WorkItemFilter `json:"filter,omitempty"`
	}
	in.Filter = filter_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.ListWorkItems", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (work_items_out_ []WorkItem, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Work_items []WorkItem `json:"work_items"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		work_items_out_ = []WorkItem(out.Work_items)
		return
	}, nil
}

// Searches the cached corpus; work items and merge requests rank by their
// RecordOpen counts.
type Search_methods struct{}

func Search() Search_methods { return Search_methods{} }

func (m Search_methods) Call(ctx context.Context, c *varlink.Connection, query_in_ string, options_in_ *SearchOptions) (work_items_out_ []WorkItem, merge_requests_out_ []MergeRequest, projects_out_ []Project, groups_out_ []Group, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, query_in_, options_in_)
	if err_ != nil {
		return
	}
	work_items_out_, merge_requests_out_, projects_out_, groups_out_, _, err_ = receive(ctx)
	return
}

func (m Search_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, query_in_ string, options_in_ *SearchOptions) (func(ctx context.Context) ([]WorkItem, []MergeRequest, []Project, []Group, uint64, error), error) {
	var in struct {
		Query   string         `json:"query"`
		Options *SearchOptions `json:"options,omitempty"`
	}
	in.Query = query_in_
	in.Options = options_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.Search", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (work_items_out_ []WorkItem, merge_requests_out_ []MergeRequest, projects_out_ []Project, groups_out_ []Group, flags uint64, err error) {
		var out struct {
			Work_items     []WorkItem     `json:"work_items"`
			Merge_requests []MergeRequest `json:"merge_requests"`
			Projects       []Project      `json:"projects"`
			Groups         []Group        `json:"groups"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		work_items_out_ = []WorkItem(out.Work_items)
		merge_requests_out_ = []MergeRequest(out.Merge_requests)
		projects_out_ = []Project(out.Projects)
		groups_out_ = []Group(out.Groups)
		return
	}, nil
}

func (m Search_methods) Upgrade(ctx context.Context, c *varlink.Connection, query_in_ string, options_in_ *SearchOptions) (func(ctx context.Context) (work_items_out_ []WorkItem, merge_requests_out_ []MergeRequest, projects_out_ []Project, groups_out_ []Group, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Query   string         `json:"query"`
		Options *SearchOptions `json:"options,omitempty"`
	}
	in.Query = query_in_
	in.Options = options_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.Search", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (work_items_out_ []WorkItem, merge_requests_out_ []MergeRequest, projects_out_ []Project, groups_out_ []Group, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Work_items     []WorkItem     `json:"work_items"`
			Merge_requests []MergeRequest `json:"merge_requests"`
			Projects       []Project      `json:"projects"`
			Groups         []Group        `json:"groups"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		work_items_out_ = []WorkItem(out.Work_items)
		merge_requests_out_ = []MergeRequest(out.Merge_requests)
		projects_out_ = []Project(out.Projects)
		groups_out_ = []Group(out.Groups)
		return
	}, nil
}

// Logs spent time on an issue or merge request; queued while GitLab is away.
type PostTime_methods struct{}

func PostTime() PostTime_methods { return PostTime_methods{} }

func (m PostTime_methods) Call(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind, duration_in_ string, summary_in_ *string) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, project_id_in_, iid_in_, kind_in_, duration_in_, summary_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m PostTime_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind, duration_in_ string, summary_in_ *string) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
		Duration   string       `json:"duration"`
		Summary    *string      `json:"summary,omitempty"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	in.Duration = duration_in_
	in.Summary = summary_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.PostTime", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m PostTime_methods) Upgrade(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind, duration_in_ string, summary_in_ *string) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
		Duration   string       `json:"duration"`
		Summary    *string      `json:"summary,omitempty"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	in.Duration = duration_in_
	in.Summary = summary_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.PostTime", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Closes an issue or merge request; queued while GitLab is away.
type Close_methods struct{}

func Close() Close_methods { return Close_methods{} }

func (m Close_methods) Call(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, project_id_in_, iid_in_, kind_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m Close_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.Close", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m Close_methods) Upgrade(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.Close", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Assigns the user to an issue or merge request; queued while GitLab is away.
type AssignSelf_methods struct{}

func AssignSelf() AssignSelf_methods { return AssignSelf_methods{} }

func (m AssignSelf_methods) Call(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, project_id_in_, iid_in_, kind_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m AssignSelf_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.AssignSelf", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m AssignSelf_methods) Upgrade(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.AssignSelf", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Removes the user from an issue's or merge request's assignees; queued while
// GitLab is away.
type UnassignSelf_methods struct{}

func UnassignSelf() UnassignSelf_methods { return UnassignSelf_methods{} }

func (m UnassignSelf_methods) Call(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, project_id_in_, iid_in_, kind_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m UnassignSelf_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.UnassignSelf", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m UnassignSelf_methods) Upgrade(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.UnassignSelf", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Creates an issue in a project, optionally under an epic. Sent to GitLab once,
// never queued. iid and web_url are absent where GitLab created the issue but
// its answer didn't say them.
type CreateWorkItem_methods struct{}

func CreateWorkItem() CreateWorkItem_methods { return CreateWorkItem_methods{} }

func (m CreateWorkItem_methods) Call(ctx context.Context, c *varlink.Connection, project_id_in_ int64, item_in_ NewWorkItem) (iid_out_ *int64, web_url_out_ *string, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, project_id_in_, item_in_)
	if err_ != nil {
		return
	}
	iid_out_, web_url_out_, _, err_ = receive(ctx)
	return
}

func (m CreateWorkItem_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, project_id_in_ int64, item_in_ NewWorkItem) (func(ctx context.Context) (*int64, *string, uint64, error), error) {
	var in struct {
		Project_id int64       `json:"project_id"`
		Item       NewWorkItem `json:"item"`
	}
	in.Project_id = project_id_in_
	in.Item = item_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.CreateWorkItem", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (iid_out_ *int64, web_url_out_ *string, flags uint64, err error) {
		var out struct {
			Iid     *int64  `json:"iid,omitempty"`
			Web_url *string `json:"web_url,omitempty"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		iid_out_ = out.Iid
		web_url_out_ = out.Web_url
		return
	}, nil
}

func (m CreateWorkItem_methods) Upgrade(ctx context.Context, c *varlink.Connection, project_id_in_ int64, item_in_ NewWorkItem) (func(ctx context.Context) (iid_out_ *int64, web_url_out_ *string, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Project_id int64       `json:"project_id"`
		Item       NewWorkItem `json:"item"`
	}
	in.Project_id = project_id_in_
	in.Item = item_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.CreateWorkItem", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (iid_out_ *int64, web_url_out_ *string, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Iid     *int64  `json:"iid,omitempty"`
			Web_url *string `json:"web_url,omitempty"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		iid_out_ = out.Iid
		web_url_out_ = out.Web_url
		return
	}, nil
}

// Counts an open of a project's work item or merge request, or of a group's
// epic. Local only: works while dormant.
type RecordOpen_methods struct{}

func RecordOpen() RecordOpen_methods { return RecordOpen_methods{} }

func (m RecordOpen_methods) Call(ctx context.Context, c *varlink.Connection, kind_in_ IssuableKind, iid_in_ int64, project_id_in_ *int64, group_id_in_ *int64) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, kind_in_, iid_in_, project_id_in_, group_id_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m RecordOpen_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, kind_in_ IssuableKind, iid_in_ int64, project_id_in_ *int64, group_id_in_ *int64) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Kind       IssuableKind `json:"kind"`
		Iid        int64        `json:"iid"`
		Project_id *int64       `json:"project_id,omitempty"`
		Group_id   *int64       `json:"group_id,omitempty"`
	}
	in.Kind = kind_in_
	in.Iid = iid_in_
	in.Project_id = project_id_in_
	in.Group_id = group_id_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.RecordOpen", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m RecordOpen_methods) Upgrade(ctx context.Context, c *varlink.Connection, kind_in_ IssuableKind, iid_in_ int64, project_id_in_ *int64, group_id_in_ *int64) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Kind       IssuableKind `json:"kind"`
		Iid        int64        `json:"iid"`
		Project_id *int64       `json:"project_id,omitempty"`
		Group_id   *int64       `json:"group_id,omitempty"`
	}
	in.Kind = kind_in_
	in.Iid = iid_in_
	in.Project_id = project_id_in_
	in.Group_id = group_id_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.RecordOpen", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Time logged in the last days (default 7): synced timelogs and queued PostTimes.
type GetHistory_methods struct{}

func GetHistory() GetHistory_methods { return GetHistory_methods{} }

func (m GetHistory_methods) Call(ctx context.Context, c *varlink.Connection, days_in_ *int64) (events_out_ []HistoryEvent, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, days_in_)
	if err_ != nil {
		return
	}
	events_out_, _, err_ = receive(ctx)
	return
}

func (m GetHistory_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, days_in_ *int64) (func(ctx context.Context) ([]HistoryEvent, uint64, error), error) {
	var in struct {
		Days *int64 `json:"days,omitempty"`
	}
	in.Days = days_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.GetHistory", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (events_out_ []HistoryEvent, flags uint64, err error) {
		var out struct {
			Events []HistoryEvent `json:"events"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		events_out_ = []HistoryEvent(out.Events)
		return
	}, nil
}

func (m GetHistory_methods) Upgrade(ctx context.Context, c *varlink.Connection, days_in_ *int64) (func(ctx context.Context) (events_out_ []HistoryEvent, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Days *int64 `json:"days,omitempty"`
	}
	in.Days = days_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.GetHistory", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (events_out_ []HistoryEvent, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Events []HistoryEvent `json:"events"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		events_out_ = []HistoryEvent(out.Events)
		return
	}, nil
}

// The user's contribution events of the last days (default 7), newest first.
type GetActivity_methods struct{}

func GetActivity() GetActivity_methods { return GetActivity_methods{} }

func (m GetActivity_methods) Call(ctx context.Context, c *varlink.Connection, days_in_ *int64) (events_out_ []ActivityEvent, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, days_in_)
	if err_ != nil {
		return
	}
	events_out_, _, err_ = receive(ctx)
	return
}

func (m GetActivity_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, days_in_ *int64) (func(ctx context.Context) ([]ActivityEvent, uint64, error), error) {
	var in struct {
		Days *int64 `json:"days,omitempty"`
	}
	in.Days = days_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.GetActivity", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (events_out_ []ActivityEvent, flags uint64, err error) {
		var out struct {
			Events []ActivityEvent `json:"events"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		events_out_ = []ActivityEvent(out.Events)
		return
	}, nil
}

func (m GetActivity_methods) Upgrade(ctx context.Context, c *varlink.Connection, days_in_ *int64) (func(ctx context.Context) (events_out_ []ActivityEvent, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Days *int64 `json:"days,omitempty"`
	}
	in.Days = days_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.GetActivity", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (events_out_ []ActivityEvent, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Events []ActivityEvent `json:"events"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		events_out_ = []ActivityEvent(out.Events)
		return
	}, nil
}

// The dead-lettered writes.
type GetFailures_methods struct{}

func GetFailures() GetFailures_methods { return GetFailures_methods{} }

func (m GetFailures_methods) Call(ctx context.Context, c *varlink.Connection) (failures_out_ []FailedTask, err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	failures_out_, _, err_ = receive(ctx)
	return
}

func (m GetFailures_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) ([]FailedTask, uint64, error), error) {
	receive, err := c.Send(ctx, "org.thehoster.forskapd.GetFailures", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (failures_out_ []FailedTask, flags uint64, err error) {
		var out struct {
			Failures []FailedTask `json:"failures"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		failures_out_ = []FailedTask(out.Failures)
		return
	}, nil
}

func (m GetFailures_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (failures_out_ []FailedTask, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.GetFailures", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (failures_out_ []FailedTask, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Failures []FailedTask `json:"failures"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		failures_out_ = []FailedTask(out.Failures)
		return
	}, nil
}

// Queues a dead-lettered write again.
type RetryFailure_methods struct{}

func RetryFailure() RetryFailure_methods { return RetryFailure_methods{} }

func (m RetryFailure_methods) Call(ctx context.Context, c *varlink.Connection, id_in_ int64) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, id_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m RetryFailure_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, id_in_ int64) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Id int64 `json:"id"`
	}
	in.Id = id_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.RetryFailure", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m RetryFailure_methods) Upgrade(ctx context.Context, c *varlink.Connection, id_in_ int64) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Id int64 `json:"id"`
	}
	in.Id = id_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.RetryFailure", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Drops a dead-lettered write.
type DismissFailure_methods struct{}

func DismissFailure() DismissFailure_methods { return DismissFailure_methods{} }

func (m DismissFailure_methods) Call(ctx context.Context, c *varlink.Connection, id_in_ int64) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, id_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m DismissFailure_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, id_in_ int64) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Id int64 `json:"id"`
	}
	in.Id = id_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.DismissFailure", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m DismissFailure_methods) Upgrade(ctx context.Context, c *varlink.Connection, id_in_ int64) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Id int64 `json:"id"`
	}
	in.Id = id_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.DismissFailure", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Drops every dead-lettered write.
type ClearFailures_methods struct{}

func ClearFailures() ClearFailures_methods { return ClearFailures_methods{} }

func (m ClearFailures_methods) Call(ctx context.Context, c *varlink.Connection) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m ClearFailures_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (uint64, error), error) {
	receive, err := c.Send(ctx, "org.thehoster.forskapd.ClearFailures", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m ClearFailures_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.ClearFailures", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// The interface version the daemon speaks, its own version and its session:
// the account while connected, else why not. Never an error.
type GetStatus_methods struct{}

func GetStatus() GetStatus_methods { return GetStatus_methods{} }

func (m GetStatus_methods) Call(ctx context.Context, c *varlink.Connection) (api_version_out_ string, daemon_version_out_ string, connected_out_ bool, reason_out_ *NotAuthReason, detail_out_ *string, host_out_ *string, username_out_ *string, user_id_out_ *int64, err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	api_version_out_, daemon_version_out_, connected_out_, reason_out_, detail_out_, host_out_, username_out_, user_id_out_, _, err_ = receive(ctx)
	return
}

func (m GetStatus_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (string, string, bool, *NotAuthReason, *string, *string, *string, *int64, uint64, error), error) {
	receive, err := c.Send(ctx, "org.thehoster.forskapd.GetStatus", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (api_version_out_ string, daemon_version_out_ string, connected_out_ bool, reason_out_ *NotAuthReason, detail_out_ *string, host_out_ *string, username_out_ *string, user_id_out_ *int64, flags uint64, err error) {
		var out struct {
			Api_version    string         `json:"api_version"`
			Daemon_version string         `json:"daemon_version"`
			Connected      bool           `json:"connected"`
			Reason         *NotAuthReason `json:"reason,omitempty"`
			Detail         *string        `json:"detail,omitempty"`
			Host           *string        `json:"host,omitempty"`
			Username       *string        `json:"username,omitempty"`
			User_id        *int64         `json:"user_id,omitempty"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		api_version_out_ = out.Api_version
		daemon_version_out_ = out.Daemon_version
		connected_out_ = out.Connected
		reason_out_ = out.Reason
		detail_out_ = out.Detail
		host_out_ = out.Host
		username_out_ = out.Username
		user_id_out_ = out.User_id
		return
	}, nil
}

func (m GetStatus_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (api_version_out_ string, daemon_version_out_ string, connected_out_ bool, reason_out_ *NotAuthReason, detail_out_ *string, host_out_ *string, username_out_ *string, user_id_out_ *int64, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.GetStatus", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (api_version_out_ string, daemon_version_out_ string, connected_out_ bool, reason_out_ *NotAuthReason, detail_out_ *string, host_out_ *string, username_out_ *string, user_id_out_ *int64, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Api_version    string         `json:"api_version"`
			Daemon_version string         `json:"daemon_version"`
			Connected      bool           `json:"connected"`
			Reason         *NotAuthReason `json:"reason,omitempty"`
			Detail         *string        `json:"detail,omitempty"`
			Host           *string        `json:"host,omitempty"`
			Username       *string        `json:"username,omitempty"`
			User_id        *int64         `json:"user_id,omitempty"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		api_version_out_ = out.Api_version
		daemon_version_out_ = out.Daemon_version
		connected_out_ = out.Connected
		reason_out_ = out.Reason
		detail_out_ = out.Detail
		host_out_ = out.Host
		username_out_ = out.Username
		user_id_out_ = out.User_id
		return
	}, nil
}

// The connected host and user, and when the token expires.
type WhoAmI_methods struct{}

func WhoAmI() WhoAmI_methods { return WhoAmI_methods{} }

func (m WhoAmI_methods) Call(ctx context.Context, c *varlink.Connection) (host_out_ string, user_id_out_ int64, username_out_ string, token_expires_at_out_ *int64, token_rotates_out_ bool, err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	host_out_, user_id_out_, username_out_, token_expires_at_out_, token_rotates_out_, _, err_ = receive(ctx)
	return
}

func (m WhoAmI_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (string, int64, string, *int64, bool, uint64, error), error) {
	receive, err := c.Send(ctx, "org.thehoster.forskapd.WhoAmI", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (host_out_ string, user_id_out_ int64, username_out_ string, token_expires_at_out_ *int64, token_rotates_out_ bool, flags uint64, err error) {
		var out struct {
			Host             string `json:"host"`
			User_id          int64  `json:"user_id"`
			Username         string `json:"username"`
			Token_expires_at *int64 `json:"token_expires_at,omitempty"`
			Token_rotates    bool   `json:"token_rotates"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		host_out_ = out.Host
		user_id_out_ = out.User_id
		username_out_ = out.Username
		token_expires_at_out_ = out.Token_expires_at
		token_rotates_out_ = out.Token_rotates
		return
	}, nil
}

func (m WhoAmI_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (host_out_ string, user_id_out_ int64, username_out_ string, token_expires_at_out_ *int64, token_rotates_out_ bool, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.WhoAmI", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (host_out_ string, user_id_out_ int64, username_out_ string, token_expires_at_out_ *int64, token_rotates_out_ bool, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Host             string `json:"host"`
			User_id          int64  `json:"user_id"`
			Username         string `json:"username"`
			Token_expires_at *int64 `json:"token_expires_at,omitempty"`
			Token_rotates    bool   `json:"token_rotates"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		host_out_ = out.Host
		user_id_out_ = out.User_id
		username_out_ = out.Username
		token_expires_at_out_ = out.Token_expires_at
		token_rotates_out_ = out.Token_rotates
		return
	}, nil
}

// Generated service interface with all methods

type orgthehosterforskapdInterface interface {
	GetAssignedWorkItems(ctx context.Context, c VarlinkCall, scope_ *Scope) error
	GetAssignedMergeRequests(ctx context.Context, c VarlinkCall, scope_ *Scope) error
	ListWorkItems(ctx context.Context, c VarlinkCall, filter_ *WorkItemFilter) error
	Search(ctx context.Context, c VarlinkCall, query_ string, options_ *SearchOptions) error
	PostTime(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind, duration_ string, summary_ *string) error
	Close(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind) error
	AssignSelf(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind) error
	UnassignSelf(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind) error
	CreateWorkItem(ctx context.Context, c VarlinkCall, project_id_ int64, item_ NewWorkItem) error
	RecordOpen(ctx context.Context, c VarlinkCall, kind_ IssuableKind, iid_ int64, project_id_ *int64, group_id_ *int64) error
	GetHistory(ctx context.Context, c VarlinkCall, days_ *int64) error
	GetActivity(ctx context.Context, c VarlinkCall, days_ *int64) error
	GetFailures(ctx context.Context, c VarlinkCall) error
	RetryFailure(ctx context.Context, c VarlinkCall, id_ int64) error
	DismissFailure(ctx context.Context, c VarlinkCall, id_ int64) error
	ClearFailures(ctx context.Context, c VarlinkCall) error
	GetStatus(ctx context.Context, c VarlinkCall) error
	WhoAmI(ctx context.Context, c VarlinkCall) error
}

// Generated service object with all methods

type VarlinkCall struct{ varlink.Call }

// Generated reply methods for all varlink errors

// The call fits the interface, but an argument's value is not acceptable (a
// number that isn't positive, a malformed duration, a blank title, …): nothing
// was sent to GitLab or stored. argument names it, a nested value by its path
// ("project_id", "iid", "duration", "options.limit", "item.title", …).
func (c *VarlinkCall) ReplyInvalidArgument(ctx context.Context, argument_ string, message_ string) error {
	var out InvalidArgument
	out.Argument = argument_
	out.Message = message_
	return c.ReplyError(ctx, "org.thehoster.forskapd.InvalidArgument", &out)
}

// The daemon has no such thing: a failure id RetryFailure or DismissFailure
// doesn't know.
func (c *VarlinkCall) ReplyNotFound(ctx context.Context, message_ string) error {
	var out NotFound
	out.Message = message_
	return c.ReplyError(ctx, "org.thehoster.forskapd.NotFound", &out)
}

// GitLab answered and refused the request.
func (c *VarlinkCall) ReplyGitlabError(ctx context.Context, message_ string, status_ *int64) error {
	var out GitlabError
	out.Message = message_
	out.Status = status_
	return c.ReplyError(ctx, "org.thehoster.forskapd.GitlabError", &out)
}

// GitLab could not be reached, or answered 429 or 5xx, and the daemon did not
// queue the call: whether GitLab carried it out is unknown.
func (c *VarlinkCall) ReplyGitlabUnavailable(ctx context.Context, message_ string) error {
	var out GitlabUnavailable
	out.Message = message_
	return c.ReplyError(ctx, "org.thehoster.forskapd.GitlabUnavailable", &out)
}

// The daemon could not do it for a reason of its own, its storage failing.
func (c *VarlinkCall) ReplyInternal(ctx context.Context, message_ string) error {
	var out Internal
	out.Message = message_
	return c.ReplyError(ctx, "org.thehoster.forskapd.Internal", &out)
}

// The daemon has no live GitLab session; detail carries the host and the
// underlying error for the reasons that have one.
func (c *VarlinkCall) ReplyNotAuthenticated(ctx context.Context, reason_ *NotAuthReason, detail_ *string) error {
	var out NotAuthenticated
	out.Reason = reason_
	out.Detail = detail_
	return c.ReplyError(ctx, "org.thehoster.forskapd.NotAuthenticated", &out)
}

// Generated reply methods for all varlink methods

func (c *VarlinkCall) ReplyGetAssignedWorkItems(ctx context.Context, work_items_ []WorkItem) error {
	var out struct {
		Work_items []WorkItem `json:"work_items"`
	}
	out.Work_items = []WorkItem(work_items_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyGetAssignedMergeRequests(ctx context.Context, merge_requests_ []MergeRequest) error {
	var out struct {
		Merge_requests []MergeRequest `json:"merge_requests"`
	}
	out.Merge_requests = []MergeRequest(merge_requests_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyListWorkItems(ctx context.Context, work_items_ []WorkItem) error {
	var out struct {
		Work_items []WorkItem `json:"work_items"`
	}
	out.Work_items = []WorkItem(work_items_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplySearch(ctx context.Context, work_items_ []WorkItem, merge_requests_ []MergeRequest, projects_ []Project, groups_ []Group) error {
	var out struct {
		Work_items     []WorkItem     `json:"work_items"`
		Merge_requests []MergeRequest `json:"merge_requests"`
		Projects       []Project      `json:"projects"`
		Groups         []Group        `json:"groups"`
	}
	out.Work_items = []WorkItem(work_items_)
	out.Merge_requests = []MergeRequest(merge_requests_)
	out.Projects = []Project(projects_)
	out.Groups = []Group(groups_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyPostTime(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyClose(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyAssignSelf(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyUnassignSelf(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyCreateWorkItem(ctx context.Context, iid_ *int64, web_url_ *string) error {
	var out struct {
		Iid     *int64  `json:"iid,omitempty"`
		Web_url *string `json:"web_url,omitempty"`
	}
	out.Iid = iid_
	out.Web_url = web_url_
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyRecordOpen(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyGetHistory(ctx context.Context, events_ []HistoryEvent) error {
	var out struct {
		Events []HistoryEvent `json:"events"`
	}
	out.Events = []HistoryEvent(events_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyGetActivity(ctx context.Context, events_ []ActivityEvent) error {
	var out struct {
		Events []ActivityEvent `json:"events"`
	}
	out.Events = []ActivityEvent(events_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyGetFailures(ctx context.Context, failures_ []FailedTask) error {
	var out struct {
		Failures []FailedTask `json:"failures"`
	}
	out.Failures = []FailedTask(failures_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyRetryFailure(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyDismissFailure(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyClearFailures(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyGetStatus(ctx context.Context, api_version_ string, daemon_version_ string, connected_ bool, reason_ *NotAuthReason, detail_ *string, host_ *string, username_ *string, user_id_ *int64) error {
	var out struct {
		Api_version    string         `json:"api_version"`
		Daemon_version string         `json:"daemon_version"`
		Connected      bool           `json:"connected"`
		Reason         *NotAuthReason `json:"reason,omitempty"`
		Detail         *string        `json:"detail,omitempty"`
		Host           *string        `json:"host,omitempty"`
		Username       *string        `json:"username,omitempty"`
		User_id        *int64         `json:"user_id,omitempty"`
	}
	out.Api_version = api_version_
	out.Daemon_version = daemon_version_
	out.Connected = connected_
	out.Reason = reason_
	out.Detail = detail_
	out.Host = host_
	out.Username = username_
	out.User_id = user_id_
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyWhoAmI(ctx context.Context, host_ string, user_id_ int64, username_ string, token_expires_at_ *int64, token_rotates_ bool) error {
	var out struct {
		Host             string `json:"host"`
		User_id          int64  `json:"user_id"`
		Username         string `json:"username"`
		Token_expires_at *int64 `json:"token_expires_at,omitempty"`
		Token_rotates    bool   `json:"token_rotates"`
	}
	out.Host = host_
	out.User_id = user_id_
	out.Username = username_
	out.Token_expires_at = token_expires_at_
	out.Token_rotates = token_rotates_
	return c.Reply(ctx, &out)
}

// Generated dummy implementations for all varlink methods

// Open issues assigned to the user, optionally only those in the scope.
func (s *VarlinkInterface) GetAssignedWorkItems(ctx context.Context, c VarlinkCall, scope_ *Scope) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.GetAssignedWorkItems")
}

// Open merge requests assigned to the user, optionally only those in the scope.
func (s *VarlinkInterface) GetAssignedMergeRequests(ctx context.Context, c VarlinkCall, scope_ *Scope) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.GetAssignedMergeRequests")
}

// The user's own issues, closed ones included, updated recently; newest-updated
// first.
func (s *VarlinkInterface) ListWorkItems(ctx context.Context, c VarlinkCall, filter_ *WorkItemFilter) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.ListWorkItems")
}

// Searches the cached corpus; work items and merge requests rank by their
// RecordOpen counts.
func (s *VarlinkInterface) Search(ctx context.Context, c VarlinkCall, query_ string, options_ *SearchOptions) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.Search")
}

// Logs spent time on an issue or merge request; queued while GitLab is away.
func (s *VarlinkInterface) PostTime(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind, duration_ string, summary_ *string) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.PostTime")
}

// Closes an issue or merge request; queued while GitLab is away.
func (s *VarlinkInterface) Close(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.Close")
}

// Assigns the user to an issue or merge request; queued while GitLab is away.
func (s *VarlinkInterface) AssignSelf(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.AssignSelf")
}

// Removes the user from an issue's or merge request's assignees; queued while
// GitLab is away.
func (s *VarlinkInterface) UnassignSelf(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.UnassignSelf")
}

// Creates an issue in a project, optionally under an epic. Sent to GitLab once,
// never queued. iid and web_url are absent where GitLab created the issue but
// its answer didn't say them.
func (s *VarlinkInterface) CreateWorkItem(ctx context.Context, c VarlinkCall, project_id_ int64, item_ NewWorkItem) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.CreateWorkItem")
}

// Counts an open of a project's work item or merge request, or of a group's
// epic. Local only: works while dormant.
func (s *VarlinkInterface) RecordOpen(ctx context.Context, c VarlinkCall, kind_ IssuableKind, iid_ int64, project_id_ *int64, group_id_ *int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.RecordOpen")
}

// Time logged in the last days (default 7): synced timelogs and queued PostTimes.
func (s *VarlinkInterface) GetHistory(ctx context.Context, c VarlinkCall, days_ *int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.GetHistory")
}

// The user's contribution events of the last days (default 7), newest first.
func (s *VarlinkInterface) GetActivity(ctx context.Context, c VarlinkCall, days_ *int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.GetActivity")
}

// The dead-lettered writes.
func (s *VarlinkInterface) GetFailures(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.GetFailures")
}

// Queues a dead-lettered write again.
func (s *VarlinkInterface) RetryFailure(ctx context.Context, c VarlinkCall, id_ int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.RetryFailure")
}

// Drops a dead-lettered write.
func (s *VarlinkInterface) DismissFailure(ctx context.Context, c VarlinkCall, id_ int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.DismissFailure")
}

// Drops every dead-lettered write.
func (s *VarlinkInterface) ClearFailures(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.ClearFailures")
}

// The interface version the daemon speaks, its own version and its session:
// the account while connected, else why not. Never an error.
func (s *VarlinkInterface) GetStatus(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.GetStatus")
}

// The connected host and user, and when the token expires.
func (s *VarlinkInterface) WhoAmI(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.WhoAmI")
}

// Generated method call dispatcher

func (s *VarlinkInterface) VarlinkDispatch(ctx context.Context, call varlink.Call, methodname string) error {
	switch methodname {
	case "GetAssignedWorkItems":
		var in struct {
			Scope *Scope `json:"scope,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.GetAssignedWorkItems(ctx, VarlinkCall{call}, in.Scope)

	case "GetAssignedMergeRequests":
		var in struct {
			Scope *Scope `json:"scope,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.GetAssignedMergeRequests(ctx, VarlinkCall{call}, in.Scope)

	case "ListWorkItems":
		var in struct {
			Filter *WorkItemFilter `json:"filter,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.ListWorkItems(ctx, VarlinkCall{call}, in.Filter)

	case "Search":
		var in struct {
			Query   string         `json:"query"`
			Options *SearchOptions `json:"options,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.Search(ctx, VarlinkCall{call}, in.Query, in.Options)

	case "PostTime":
		var in struct {
			Project_id int64        `json:"project_id"`
			Iid        int64        `json:"iid"`
			Kind       IssuableKind `json:"kind"`
			Duration   string       `json:"duration"`
			Summary    *string      `json:"summary,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.PostTime(ctx, VarlinkCall{call}, in.Project_id, in.Iid, in.Kind, in.Duration, in.Summary)

	case "Close":
		var in struct {
			Project_id int64        `json:"project_id"`
			Iid        int64        `json:"iid"`
			Kind       IssuableKind `json:"kind"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.Close(ctx, VarlinkCall{call}, in.Project_id, in.Iid, in.Kind)

	case "AssignSelf":
		var in struct {
			Project_id int64        `json:"project_id"`
			Iid        int64        `json:"iid"`
			Kind       IssuableKind `json:"kind"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.AssignSelf(ctx, VarlinkCall{call}, in.Project_id, in.Iid, in.Kind)

	case "UnassignSelf":
		var in struct {
			Project_id int64        `json:"project_id"`
			Iid        int64        `json:"iid"`
			Kind       IssuableKind `json:"kind"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.UnassignSelf(ctx, VarlinkCall{call}, in.Project_id, in.Iid, in.Kind)

	case "CreateWorkItem":
		var in struct {
			Project_id int64       `json:"project_id"`
			Item       NewWorkItem `json:"item"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.CreateWorkItem(ctx, VarlinkCall{call}, in.Project_id, in.Item)

	case "RecordOpen":
		var in struct {
			Kind       IssuableKind `json:"kind"`
			Iid        int64        `json:"iid"`
			Project_id *int64       `json:"project_id,omitempty"`
			Group_id   *int64       `json:"group_id,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.RecordOpen(ctx, VarlinkCall{call}, in.Kind, in.Iid, in.Project_id, in.Group_id)

	case "GetHistory":
		var in struct {
			Days *int64 `json:"days,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.GetHistory(ctx, VarlinkCall{call}, in.Days)

	case "GetActivity":
		var in struct {
			Days *int64 `json:"days,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.GetActivity(ctx, VarlinkCall{call}, in.Days)

	case "GetFailures":
		return s.orgthehosterforskapdInterface.GetFailures(ctx, VarlinkCall{call})

	case "RetryFailure":
		var in struct {
			Id int64 `json:"id"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.RetryFailure(ctx, VarlinkCall{call}, in.Id)

	case "DismissFailure":
		var in struct {
			Id int64 `json:"id"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.DismissFailure(ctx, VarlinkCall{call}, in.Id)

	case "ClearFailures":
		return s.orgthehosterforskapdInterface.ClearFailures(ctx, VarlinkCall{call})

	case "GetStatus":
		return s.orgthehosterforskapdInterface.GetStatus(ctx, VarlinkCall{call})

	case "WhoAmI":
		return s.orgthehosterforskapdInterface.WhoAmI(ctx, VarlinkCall{call})

	default:
		return call.ReplyMethodNotFound(ctx, methodname)
	}
}

// Generated varlink interface name

func (s *VarlinkInterface) VarlinkGetName() string {
	return `org.thehoster.forskapd`
}

// Generated varlink interface description

func (s *VarlinkInterface) VarlinkGetDescription() string {
	return `interface org.thehoster.forskapd

# A work item named by where it lives and its number.
type WorkItemRef (
  # The project of the work item named, or
  project_id: ?int,
  # its group: exactly one of the two is set.
  group_id: ?int,
  iid: int,
  # "epic", …; absent when the naming side doesn't say.
  type: ?string,
  title: ?string,
  # Absolute; absent when unknown.
  web_url: ?string
)

# An issue, task, epic, …: GitLab's work item, of a project or of a group.
type WorkItem (
  # Global work item ID, unique across the GitLab instance.
  id: int,
  # Number within its project or group ("#42" of an issue, "&5" of an epic).
  iid: int,
  # "issue", "task", "incident", "test_case", "epic", …
  type: string,
  # The project of an issue, task, …; absent for an epic.
  project_id: ?int,
  # The group of an epic; absent for the rest.
  group_id: ?int,
  # Full path of that project ("team/api") or group ("team"): the stored
  # one's, else the one in web_url; absent when neither gives it.
  namespace_path: ?string,
  title: string,
  web_url: string,
  # "opened" or "closed".
  state: string,
  # The epic an issue belongs to; absent when it has none, and for an epic.
  parent: ?WorkItemRef,
  # Seconds spent on it, GitLab's time_stats.total_time_spent: 0 when none is
  # logged; absent for an epic.
  time_spent: ?int,
  # Board column the issue sits in: the first of its labels that is a list on
  # the project's issue boards, else its state ("opened", "closed": a board's
  # Open and Closed lists). Absent when the project's boards never synced, and
  # for an epic.
  board_column: ?string,
  # Opens recorded through RecordOpen (within usage.retention_hours).
  open_count: int,
  # File of the project's avatar, see Project.avatar; absent when none, and
  # for an epic.
  project_avatar: ?string,
  # Unix seconds, GitLab's updated_at as of the last sync; absent when unknown.
  updated_at: ?int
)

# What a write or RecordOpen targets; an issue is a work_item.
type IssuableKind (work_item, merge_request)

# Where a HistoryEvent comes from.
type HistorySource (
  # A timelog synced from GitLab.
  gitlab,
  # A PostTime still waiting in the retry queue.
  queued
)

# Time logged on an issue or merge request.
type HistoryEvent (
  # Unix seconds: spent_at for a synced entry, the enqueue time for a queued one.
  timestamp: int,
  source: HistorySource,
  # What the time was logged on.
  kind: IssuableKind,
  project_id: int,
  iid: int,
  # Absent on a queued event whose issuable is not in the caches.
  title: ?string,
  # Absent like title.
  web_url: ?string,
  # Seconds; set on a synced entry, absent on a queued one.
  time_spent: ?int,
  # A queued PostTime's duration as it was given ("1h30m"); absent on a synced
  # entry. The daemon can't turn it into seconds: GitLab's "1d" and "1w" depend
  # on the instance's settings.
  duration: ?string,
  # The timelog's note; absent when it has none.
  summary: ?string
)

# One of the user's contribution events (GitLab's GET /events).
type ActivityEvent (
  # Unix seconds.
  timestamp: int,
  # GitLab's action name: "pushed to", "opened", "commented on", "accepted",
  # "joined", …
  action: string,
  # "Issue", "MergeRequest", "Milestone", …; of a comment, what was commented
  # on; absent on pushes and membership events.
  target_type: ?string,
  # The target's number in its project, where it has one.
  target_iid: ?int,
  target_title: ?string,
  # Absent for events outside a project.
  project_id: ?int,
  # Absent when neither the project nor the item is in the store.
  project_path: ?string,
  # The issue or MR, a pushed branch's commits, else the project; absent when
  # unknown.
  web_url: ?string,
  # Pushes only: the branch or tag.
  ref: ?string,
  # Pushes only.
  commit_count: ?int,
  # Pushes only: the newest commit's title; absent when the ref was deleted.
  commit_title: ?string,
  # What the event did: a comment's first line (at most 200 characters, a cut
  # one ends in …), a push's commit_title; absent for every other event.
  description: ?string
)

# A write that exhausted its retry window or was rejected while draining.
type FailedTask (
  # Handle for RetryFailure and DismissFailure.
  id: int,
  # Which write failed: "PostTime", "Close", "AssignSelf", "UnassignSelf".
  op: string,
  kind: IssuableKind,
  project_id: int,
  iid: int,
  # Operation-specific summary, e.g. the duration.
  detail: string,
  # The GitLab error that dead-lettered it.
  error: string,
  # Unix seconds.
  queued_at: int,
  # Unix seconds.
  failed_at: int
)

type MergeRequest (
  # Global MR ID, unique across the GitLab instance.
  id: int,
  # Per-project MR number (the "!7" shown in the UI).
  iid: int,
  project_id: int,
  title: string,
  web_url: string,
  # "opened", "closed", "merged" or "locked".
  state: string,
  # Assignee usernames, as of the last sync.
  assignees: []string,
  # Opens recorded through RecordOpen (within usage.retention_hours).
  open_count: int,
  # File of the project's avatar, see Project.avatar; absent when none.
  project_avatar: ?string,
  # The project's full path ("team/api"): the stored project's, else the one
  # in web_url; absent when neither gives it.
  project_path: ?string,
  # Unix seconds, GitLab's updated_at as of the last sync; absent when unknown.
  updated_at: ?int
)

# A project the user is a member of.
type Project (
  id: int,
  name: string,
  # Full namespace path ("team/backend/api").
  full_path: string,
  web_url: string,
  # Absolute path of the avatar image on the daemon's machine; absent when
  # the daemon has none.
  avatar: ?string,
  # Whether the project is archived (read-only on GitLab).
  archived: bool
)

# A group the user is a member of.
type Group (
  id: int,
  name: string,
  # Full group path ("team/backend").
  full_path: string,
  web_url: string
)

# The call fits the interface, but an argument's value is not acceptable (a
# number that isn't positive, a malformed duration, a blank title, …): nothing
# was sent to GitLab or stored. argument names it, a nested value by its path
# ("project_id", "iid", "duration", "options.limit", "item.title", …).
error InvalidArgument (argument: string, message: string)

# The daemon has no such thing: a failure id RetryFailure or DismissFailure
# doesn't know.
error NotFound (message: string)

# GitLab answered and refused the request.
error GitlabError (
  message: string,
  # The HTTP status of GitLab's answer, 401 for a token it no longer takes;
  # absent where the daemon has none (an answer it can't read).
  status: ?int
)

# GitLab could not be reached, or answered 429 or 5xx, and the daemon did not
# queue the call: whether GitLab carried it out is unknown.
error GitlabUnavailable (message: string)

# The daemon could not do it for a reason of its own, its storage failing.
error Internal (message: string)

# Why the daemon has no GitLab session.
type NotAuthReason (
  # No credentials stored (never logged in).
  no_credentials,
  # Reading the OS keychain failed (detail: the error).
  keychain_error,
  # Credentials exist but GitLab could not be reached (detail set); heals by
  # itself.
  unreachable,
  # Credentials exist but GitLab rejected the token (detail set).
  token_rejected,
  # The user logged out.
  logged_out
)

# The daemon has no live GitLab session; detail carries the host and the
# underlying error for the reasons that have one.
error NotAuthenticated (reason: ?NotAuthReason, detail: ?string)

# The projects and groups a call keeps to: an item passes if it lies in any of
# them. Nothing listed is no filter.
type Scope (
  # Project IDs.
  projects: ?[]int,
  # Group paths ("team/backend"), subgroups included.
  groups: ?[]string
)

# Open issues assigned to the user, optionally only those in the scope.
method GetAssignedWorkItems(scope: ?Scope) -> (work_items: []WorkItem)

# Open merge requests assigned to the user, optionally only those in the scope.
method GetAssignedMergeRequests(scope: ?Scope) -> (merge_requests: []MergeRequest)

# Which of ListWorkItems' lists: the issues the user authored, or is assigned to.
type WorkItemRole (author, assignee)

# The states ListWorkItems filters by; WorkItem.state carries them.
type WorkItemState (opened, closed)

# Which of the user's own issues ListWorkItems lists; nothing set is all of
# them.
type WorkItemFilter (
  # One of the two lists; absent: both, an issue in both listed once.
  role: ?WorkItemRole,
  # Unix seconds: only issues updated at or after it.
  updated_after: ?int,
  # Only issues in one of these states; absent or empty: both.
  states: ?[]WorkItemState
)

# The user's own issues, closed ones included, updated recently; newest-updated
# first.
method ListWorkItems(filter: ?WorkItemFilter) -> (work_items: []WorkItem)

# The result sets of a Search.
type SearchKind (work_items, merge_requests, projects, groups)

# How a Search narrows its results; nothing set narrows nothing.
type SearchOptions (
  # The result sets to fill; absent or empty: all four.
  kinds: ?[]SearchKind,
  # Caps each result set; issues and epics share theirs. Absent: 50.
  limit: ?int,
  # Keeps every result set to these projects and groups.
  scope: ?Scope,
  # Keeps only the work items of these types ("issue", "task", "epic", …),
  # compared case-insensitively; absent or empty: every type.
  types: ?[]string,
  # Leaves out the work items of these types, compared the same way.
  exclude_types: ?[]string,
  # With an empty query, every row matches instead of only the frequently
  # opened ones; absent: false. A query that isn't empty ignores it. Since 1.1.
  match_all: ?bool
)

# Searches the cached corpus; work items and merge requests rank by their
# RecordOpen counts.
method Search(query: string, options: ?SearchOptions) -> (work_items: []WorkItem, merge_requests: []MergeRequest, projects: []Project, groups: []Group)

# Logs spent time on an issue or merge request; queued while GitLab is away.
method PostTime(project_id: int, iid: int, kind: IssuableKind, duration: string, summary: ?string) -> ()

# Closes an issue or merge request; queued while GitLab is away.
method Close(project_id: int, iid: int, kind: IssuableKind) -> ()

# Assigns the user to an issue or merge request; queued while GitLab is away.
method AssignSelf(project_id: int, iid: int, kind: IssuableKind) -> ()

# Removes the user from an issue's or merge request's assignees; queued while
# GitLab is away.
method UnassignSelf(project_id: int, iid: int, kind: IssuableKind) -> ()

# The issue CreateWorkItem files.
type NewWorkItem (
  # Not blank.
  title: string,
  # GitLab Markdown.
  description: ?string,
  # Label names, none with a comma; GitLab creates the ones the project lacks.
  labels: ?[]string,
  # Assigns the issue to the user; absent: nobody is assigned.
  assign_self: ?bool,
  # The epic to put the issue under, by its group_id and iid (type absent or
  # "epic", title and web_url ignored); needs GitLab Premium.
  parent: ?WorkItemRef
)

# Creates an issue in a project, optionally under an epic. Sent to GitLab once,
# never queued. iid and web_url are absent where GitLab created the issue but
# its answer didn't say them.
method CreateWorkItem(project_id: int, item: NewWorkItem) -> (iid: ?int, web_url: ?string)

# Counts an open of a project's work item or merge request, or of a group's
# epic. Local only: works while dormant.
method RecordOpen(kind: IssuableKind, iid: int, project_id: ?int, group_id: ?int) -> ()

# Time logged in the last days (default 7): synced timelogs and queued PostTimes.
method GetHistory(days: ?int) -> (events: []HistoryEvent)

# The user's contribution events of the last days (default 7), newest first.
method GetActivity(days: ?int) -> (events: []ActivityEvent)

# The dead-lettered writes.
method GetFailures() -> (failures: []FailedTask)

# Queues a dead-lettered write again.
method RetryFailure(id: int) -> ()

# Drops a dead-lettered write.
method DismissFailure(id: int) -> ()

# Drops every dead-lettered write.
method ClearFailures() -> ()

# The interface version the daemon speaks, its own version and its session:
# the account while connected, else why not. Never an error.
method GetStatus() -> (api_version: string, daemon_version: string, connected: bool, reason: ?NotAuthReason, detail: ?string, host: ?string, username: ?string, user_id: ?int)

# The connected host and user, and when the token expires.
method WhoAmI() -> (host: string, user_id: int, username: string, token_expires_at: ?int, token_rotates: bool)
`
}

// Generated service interface

type VarlinkInterface struct {
	orgthehosterforskapdInterface
}

func VarlinkNew(m orgthehosterforskapdInterface) *VarlinkInterface {
	return &VarlinkInterface{m}
}
