// Code generated by github.com/varlink/go/cmd/varlink-go-interface-generator, DO NOT EDIT.

package orgthehosterforskapd

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/varlink/go/varlink"
)

// Generated type declarations

type Issue struct {
	Id             int64  `json:"id"`
	Iid            int64  `json:"iid"`
	Project_id     int64  `json:"project_id"`
	Title          string `json:"title"`
	Web_url        string `json:"web_url"`
	State          string `json:"state"`
	Parent         string `json:"parent"`
	Total_time     string `json:"total_time"`
	Graph_status   string `json:"graph_status"`
	Open_count     int64  `json:"open_count"`
	Project_avatar string `json:"project_avatar"`
}

type IssuableKind string

type HistoryEvent struct {
	Timestamp  int64        `json:"timestamp"`
	Source     string       `json:"source"`
	Kind       IssuableKind `json:"kind"`
	Project_id int64        `json:"project_id"`
	Iid        int64        `json:"iid"`
	Title      string       `json:"title"`
	Web_url    string       `json:"web_url"`
	Duration   string       `json:"duration"`
	Summary    string       `json:"summary"`
}

type ActivityEvent struct {
	Timestamp    int64   `json:"timestamp"`
	Action       string  `json:"action"`
	Target_type  string  `json:"target_type"`
	Target_iid   *int64  `json:"target_iid,omitempty"`
	Target_title *string `json:"target_title,omitempty"`
	Project_id   int64   `json:"project_id"`
	Project_path *string `json:"project_path,omitempty"`
	Web_url      *string `json:"web_url,omitempty"`
	Ref          *string `json:"ref,omitempty"`
	Commit_count *int64  `json:"commit_count,omitempty"`
	Commit_title *string `json:"commit_title,omitempty"`
	Description  *string `json:"description,omitempty"`
}

type FailedTask struct {
	Id         int64        `json:"id"`
	Op         string       `json:"op"`
	Kind       IssuableKind `json:"kind"`
	Project_id int64        `json:"project_id"`
	Iid        int64        `json:"iid"`
	Detail     string       `json:"detail"`
	Error      string       `json:"error"`
	Queued_at  int64        `json:"queued_at"`
	Failed_at  int64        `json:"failed_at"`
}

type MergeRequest struct {
	Id             int64    `json:"id"`
	Iid            int64    `json:"iid"`
	Project_id     int64    `json:"project_id"`
	Title          string   `json:"title"`
	Web_url        string   `json:"web_url"`
	State          string   `json:"state"`
	Assignees      []string `json:"assignees"`
	Open_count     int64    `json:"open_count"`
	Project_avatar string   `json:"project_avatar"`
}

type Project struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	Path    string `json:"path"`
	Web_url string `json:"web_url"`
	Avatar  string `json:"avatar"`
}

type Group struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	Path    string `json:"path"`
	Web_url string `json:"web_url"`
}

type SyncJobStatus string

type SyncJob struct {
	Key           string        `json:"key"`
	Status        SyncJobStatus `json:"status"`
	Last_ok       *int64        `json:"last_ok,omitempty"`
	Next_due      *int64        `json:"next_due,omitempty"`
	Running_since *int64        `json:"running_since,omitempty"`
	Failures      int64         `json:"failures"`
	Last_error    *string       `json:"last_error,omitempty"`
}

type Epic struct {
	Id         int64  `json:"id"`
	Iid        int64  `json:"iid"`
	Group_id   int64  `json:"group_id"`
	Title      string `json:"title"`
	Web_url    string `json:"web_url"`
	State      string `json:"state"`
	Open_count int64  `json:"open_count"`
}

type NotAuthReason string

type GitlabError struct {
	Message string `json:"message"`
}

func (e GitlabError) Error() string {
	s := "org.thehoster.forskapd.GitlabError"
	s += fmt.Sprintf("(Message: %v)", e.Message)
	return s
}

type NotAuthenticated struct {
	Reason *NotAuthReason `json:"reason,omitempty"`
	Detail *string        `json:"detail,omitempty"`
}

func (e NotAuthenticated) Error() string {
	s := "org.thehoster.forskapd.NotAuthenticated"
	s += fmt.Sprintf("(Reason: %v, Detail: %v)", e.Reason, e.Detail)
	return s
}

func Dispatch_Error(err error) error {
	if e, ok := err.(*varlink.Error); ok {
		switch e.Name {
		case "org.thehoster.forskapd.GitlabError":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param GitlabError
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		case "org.thehoster.forskapd.NotAuthenticated":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param NotAuthenticated
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		}
	}
	return err
}

// Generated client method calls

type GetAssignedIssues_methods struct{}

func GetAssignedIssues() GetAssignedIssues_methods { return GetAssignedIssues_methods{} }

func (m GetAssignedIssues_methods) Call(ctx context.Context, c *varlink.Connection, groups_in_ *[]string) (issues_out_ []Issue, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, groups_in_)
	if err_ != nil {
		return
	}
	issues_out_, _, err_ = receive(ctx)
	return
}

func (m GetAssignedIssues_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, groups_in_ *[]string) (func(ctx context.Context) ([]Issue, uint64, error), error) {
	var in struct {
		Groups *[]string `json:"groups,omitempty"`
	}
	in.Groups = groups_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.GetAssignedIssues", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (issues_out_ []Issue, flags uint64, err error) {
		var out struct {
			Issues []Issue `json:"issues"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		issues_out_ = []Issue(out.Issues)
		return
	}, nil
}

func (m GetAssignedIssues_methods) Upgrade(ctx context.Context, c *varlink.Connection, groups_in_ *[]string) (func(ctx context.Context) (issues_out_ []Issue, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Groups *[]string `json:"groups,omitempty"`
	}
	in.Groups = groups_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.GetAssignedIssues", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (issues_out_ []Issue, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Issues []Issue `json:"issues"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		issues_out_ = []Issue(out.Issues)
		return
	}, nil
}

type GetAssignedMergeRequests_methods struct{}

func GetAssignedMergeRequests() GetAssignedMergeRequests_methods {
	return GetAssignedMergeRequests_methods{}
}

func (m GetAssignedMergeRequests_methods) Call(ctx context.Context, c *varlink.Connection, groups_in_ *[]string) (merge_requests_out_ []MergeRequest, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, groups_in_)
	if err_ != nil {
		return
	}
	merge_requests_out_, _, err_ = receive(ctx)
	return
}

func (m GetAssignedMergeRequests_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, groups_in_ *[]string) (func(ctx context.Context) ([]MergeRequest, uint64, error), error) {
	var in struct {
		Groups *[]string `json:"groups,omitempty"`
	}
	in.Groups = groups_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.GetAssignedMergeRequests", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (merge_requests_out_ []MergeRequest, flags uint64, err error) {
		var out struct {
			Merge_requests []MergeRequest `json:"merge_requests"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		merge_requests_out_ = []MergeRequest(out.Merge_requests)
		return
	}, nil
}

func (m GetAssignedMergeRequests_methods) Upgrade(ctx context.Context, c *varlink.Connection, groups_in_ *[]string) (func(ctx context.Context) (merge_requests_out_ []MergeRequest, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Groups *[]string `json:"groups,omitempty"`
	}
	in.Groups = groups_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.GetAssignedMergeRequests", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (merge_requests_out_ []MergeRequest, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Merge_requests []MergeRequest `json:"merge_requests"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		merge_requests_out_ = []MergeRequest(out.Merge_requests)
		return
	}, nil
}

type Search_methods struct{}

func Search() Search_methods { return Search_methods{} }

func (m Search_methods) Call(ctx context.Context, c *varlink.Connection, query_in_ string, kinds_in_ *[]string, limit_in_ *int64) (issues_out_ []Issue, merge_requests_out_ []MergeRequest, projects_out_ []Project, groups_out_ []Group, epics_out_ []Epic, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, query_in_, kinds_in_, limit_in_)
	if err_ != nil {
		return
	}
	issues_out_, merge_requests_out_, projects_out_, groups_out_, epics_out_, _, err_ = receive(ctx)
	return
}

func (m Search_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, query_in_ string, kinds_in_ *[]string, limit_in_ *int64) (func(ctx context.Context) ([]Issue, []MergeRequest, []Project, []Group, []Epic, uint64, error), error) {
	var in struct {
		Query string    `json:"query"`
		Kinds *[]string `json:"kinds,omitempty"`
		Limit *int64    `json:"limit,omitempty"`
	}
	in.Query = query_in_
	in.Kinds = kinds_in_
	in.Limit = limit_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.Search", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (issues_out_ []Issue, merge_requests_out_ []MergeRequest, projects_out_ []Project, groups_out_ []Group, epics_out_ []Epic, flags uint64, err error) {
		var out struct {
			Issues         []Issue        `json:"issues"`
			Merge_requests []MergeRequest `json:"merge_requests"`
			Projects       []Project      `json:"projects"`
			Groups         []Group        `json:"groups"`
			Epics          []Epic         `json:"epics"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		issues_out_ = []Issue(out.Issues)
		merge_requests_out_ = []MergeRequest(out.Merge_requests)
		projects_out_ = []Project(out.Projects)
		groups_out_ = []Group(out.Groups)
		epics_out_ = []Epic(out.Epics)
		return
	}, nil
}

func (m Search_methods) Upgrade(ctx context.Context, c *varlink.Connection, query_in_ string, kinds_in_ *[]string, limit_in_ *int64) (func(ctx context.Context) (issues_out_ []Issue, merge_requests_out_ []MergeRequest, projects_out_ []Project, groups_out_ []Group, epics_out_ []Epic, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Query string    `json:"query"`
		Kinds *[]string `json:"kinds,omitempty"`
		Limit *int64    `json:"limit,omitempty"`
	}
	in.Query = query_in_
	in.Kinds = kinds_in_
	in.Limit = limit_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.Search", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (issues_out_ []Issue, merge_requests_out_ []MergeRequest, projects_out_ []Project, groups_out_ []Group, epics_out_ []Epic, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Issues         []Issue        `json:"issues"`
			Merge_requests []MergeRequest `json:"merge_requests"`
			Projects       []Project      `json:"projects"`
			Groups         []Group        `json:"groups"`
			Epics          []Epic         `json:"epics"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		issues_out_ = []Issue(out.Issues)
		merge_requests_out_ = []MergeRequest(out.Merge_requests)
		projects_out_ = []Project(out.Projects)
		groups_out_ = []Group(out.Groups)
		epics_out_ = []Epic(out.Epics)
		return
	}, nil
}

type PostTime_methods struct{}

func PostTime() PostTime_methods { return PostTime_methods{} }

func (m PostTime_methods) Call(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind, duration_in_ string, summary_in_ *string) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, project_id_in_, iid_in_, kind_in_, duration_in_, summary_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m PostTime_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind, duration_in_ string, summary_in_ *string) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
		Duration   string       `json:"duration"`
		Summary    *string      `json:"summary,omitempty"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	in.Duration = duration_in_
	in.Summary = summary_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.PostTime", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m PostTime_methods) Upgrade(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind, duration_in_ string, summary_in_ *string) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
		Duration   string       `json:"duration"`
		Summary    *string      `json:"summary,omitempty"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	in.Duration = duration_in_
	in.Summary = summary_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.PostTime", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type Close_methods struct{}

func Close() Close_methods { return Close_methods{} }

func (m Close_methods) Call(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, project_id_in_, iid_in_, kind_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m Close_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.Close", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m Close_methods) Upgrade(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.Close", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type AssignSelf_methods struct{}

func AssignSelf() AssignSelf_methods { return AssignSelf_methods{} }

func (m AssignSelf_methods) Call(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, project_id_in_, iid_in_, kind_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m AssignSelf_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.AssignSelf", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m AssignSelf_methods) Upgrade(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.AssignSelf", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type UnassignSelf_methods struct{}

func UnassignSelf() UnassignSelf_methods { return UnassignSelf_methods{} }

func (m UnassignSelf_methods) Call(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, project_id_in_, iid_in_, kind_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m UnassignSelf_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.UnassignSelf", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m UnassignSelf_methods) Upgrade(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.UnassignSelf", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type RecordOpen_methods struct{}

func RecordOpen() RecordOpen_methods { return RecordOpen_methods{} }

func (m RecordOpen_methods) Call(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, project_id_in_, iid_in_, kind_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m RecordOpen_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.RecordOpen", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m RecordOpen_methods) Upgrade(ctx context.Context, c *varlink.Connection, project_id_in_ int64, iid_in_ int64, kind_in_ IssuableKind) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Project_id int64        `json:"project_id"`
		Iid        int64        `json:"iid"`
		Kind       IssuableKind `json:"kind"`
	}
	in.Project_id = project_id_in_
	in.Iid = iid_in_
	in.Kind = kind_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.RecordOpen", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type RecordEpicOpen_methods struct{}

func RecordEpicOpen() RecordEpicOpen_methods { return RecordEpicOpen_methods{} }

func (m RecordEpicOpen_methods) Call(ctx context.Context, c *varlink.Connection, group_id_in_ int64, iid_in_ int64) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, group_id_in_, iid_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m RecordEpicOpen_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, group_id_in_ int64, iid_in_ int64) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Group_id int64 `json:"group_id"`
		Iid      int64 `json:"iid"`
	}
	in.Group_id = group_id_in_
	in.Iid = iid_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.RecordEpicOpen", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m RecordEpicOpen_methods) Upgrade(ctx context.Context, c *varlink.Connection, group_id_in_ int64, iid_in_ int64) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Group_id int64 `json:"group_id"`
		Iid      int64 `json:"iid"`
	}
	in.Group_id = group_id_in_
	in.Iid = iid_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.RecordEpicOpen", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type ClearCache_methods struct{}

func ClearCache() ClearCache_methods { return ClearCache_methods{} }

func (m ClearCache_methods) Call(ctx context.Context, c *varlink.Connection, scope_in_ *[]string) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, scope_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m ClearCache_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, scope_in_ *[]string) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Scope *[]string `json:"scope,omitempty"`
	}
	in.Scope = scope_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.ClearCache", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m ClearCache_methods) Upgrade(ctx context.Context, c *varlink.Connection, scope_in_ *[]string) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Scope *[]string `json:"scope,omitempty"`
	}
	in.Scope = scope_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.ClearCache", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type GetHistory_methods struct{}

func GetHistory() GetHistory_methods { return GetHistory_methods{} }

func (m GetHistory_methods) Call(ctx context.Context, c *varlink.Connection, days_in_ *int64) (events_out_ []HistoryEvent, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, days_in_)
	if err_ != nil {
		return
	}
	events_out_, _, err_ = receive(ctx)
	return
}

func (m GetHistory_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, days_in_ *int64) (func(ctx context.Context) ([]HistoryEvent, uint64, error), error) {
	var in struct {
		Days *int64 `json:"days,omitempty"`
	}
	in.Days = days_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.GetHistory", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (events_out_ []HistoryEvent, flags uint64, err error) {
		var out struct {
			Events []HistoryEvent `json:"events"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		events_out_ = []HistoryEvent(out.Events)
		return
	}, nil
}

func (m GetHistory_methods) Upgrade(ctx context.Context, c *varlink.Connection, days_in_ *int64) (func(ctx context.Context) (events_out_ []HistoryEvent, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Days *int64 `json:"days,omitempty"`
	}
	in.Days = days_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.GetHistory", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (events_out_ []HistoryEvent, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Events []HistoryEvent `json:"events"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		events_out_ = []HistoryEvent(out.Events)
		return
	}, nil
}

type GetActivity_methods struct{}

func GetActivity() GetActivity_methods { return GetActivity_methods{} }

func (m GetActivity_methods) Call(ctx context.Context, c *varlink.Connection, days_in_ *int64) (events_out_ []ActivityEvent, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, days_in_)
	if err_ != nil {
		return
	}
	events_out_, _, err_ = receive(ctx)
	return
}

func (m GetActivity_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, days_in_ *int64) (func(ctx context.Context) ([]ActivityEvent, uint64, error), error) {
	var in struct {
		Days *int64 `json:"days,omitempty"`
	}
	in.Days = days_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.GetActivity", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (events_out_ []ActivityEvent, flags uint64, err error) {
		var out struct {
			Events []ActivityEvent `json:"events"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		events_out_ = []ActivityEvent(out.Events)
		return
	}, nil
}

func (m GetActivity_methods) Upgrade(ctx context.Context, c *varlink.Connection, days_in_ *int64) (func(ctx context.Context) (events_out_ []ActivityEvent, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Days *int64 `json:"days,omitempty"`
	}
	in.Days = days_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.GetActivity", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (events_out_ []ActivityEvent, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Events []ActivityEvent `json:"events"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		events_out_ = []ActivityEvent(out.Events)
		return
	}, nil
}

type GetFailures_methods struct{}

func GetFailures() GetFailures_methods { return GetFailures_methods{} }

func (m GetFailures_methods) Call(ctx context.Context, c *varlink.Connection) (failures_out_ []FailedTask, err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	failures_out_, _, err_ = receive(ctx)
	return
}

func (m GetFailures_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) ([]FailedTask, uint64, error), error) {
	receive, err := c.Send(ctx, "org.thehoster.forskapd.GetFailures", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (failures_out_ []FailedTask, flags uint64, err error) {
		var out struct {
			Failures []FailedTask `json:"failures"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		failures_out_ = []FailedTask(out.Failures)
		return
	}, nil
}

func (m GetFailures_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (failures_out_ []FailedTask, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.GetFailures", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (failures_out_ []FailedTask, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Failures []FailedTask `json:"failures"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		failures_out_ = []FailedTask(out.Failures)
		return
	}, nil
}

type RetryFailure_methods struct{}

func RetryFailure() RetryFailure_methods { return RetryFailure_methods{} }

func (m RetryFailure_methods) Call(ctx context.Context, c *varlink.Connection, id_in_ int64) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, id_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m RetryFailure_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, id_in_ int64) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Id int64 `json:"id"`
	}
	in.Id = id_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.RetryFailure", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m RetryFailure_methods) Upgrade(ctx context.Context, c *varlink.Connection, id_in_ int64) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Id int64 `json:"id"`
	}
	in.Id = id_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.RetryFailure", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type DismissFailure_methods struct{}

func DismissFailure() DismissFailure_methods { return DismissFailure_methods{} }

func (m DismissFailure_methods) Call(ctx context.Context, c *varlink.Connection, id_in_ int64) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, id_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m DismissFailure_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, id_in_ int64) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Id int64 `json:"id"`
	}
	in.Id = id_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.DismissFailure", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m DismissFailure_methods) Upgrade(ctx context.Context, c *varlink.Connection, id_in_ int64) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Id int64 `json:"id"`
	}
	in.Id = id_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.DismissFailure", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type ClearFailures_methods struct{}

func ClearFailures() ClearFailures_methods { return ClearFailures_methods{} }

func (m ClearFailures_methods) Call(ctx context.Context, c *varlink.Connection) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m ClearFailures_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (uint64, error), error) {
	receive, err := c.Send(ctx, "org.thehoster.forskapd.ClearFailures", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m ClearFailures_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.ClearFailures", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type GetSyncJobs_methods struct{}

func GetSyncJobs() GetSyncJobs_methods { return GetSyncJobs_methods{} }

func (m GetSyncJobs_methods) Call(ctx context.Context, c *varlink.Connection) (jobs_out_ []SyncJob, paused_until_out_ *int64, err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	jobs_out_, paused_until_out_, _, err_ = receive(ctx)
	return
}

func (m GetSyncJobs_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) ([]SyncJob, *int64, uint64, error), error) {
	receive, err := c.Send(ctx, "org.thehoster.forskapd.GetSyncJobs", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (jobs_out_ []SyncJob, paused_until_out_ *int64, flags uint64, err error) {
		var out struct {
			Jobs         []SyncJob `json:"jobs"`
			Paused_until *int64    `json:"paused_until,omitempty"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		jobs_out_ = []SyncJob(out.Jobs)
		paused_until_out_ = out.Paused_until
		return
	}, nil
}

func (m GetSyncJobs_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (jobs_out_ []SyncJob, paused_until_out_ *int64, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.GetSyncJobs", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (jobs_out_ []SyncJob, paused_until_out_ *int64, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Jobs         []SyncJob `json:"jobs"`
			Paused_until *int64    `json:"paused_until,omitempty"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		jobs_out_ = []SyncJob(out.Jobs)
		paused_until_out_ = out.Paused_until
		return
	}, nil
}

type Login_methods struct{}

func Login() Login_methods { return Login_methods{} }

func (m Login_methods) Call(ctx context.Context, c *varlink.Connection, host_in_ string, token_in_ string) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, host_in_, token_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m Login_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, host_in_ string, token_in_ string) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Host  string `json:"host"`
		Token string `json:"token"`
	}
	in.Host = host_in_
	in.Token = token_in_
	receive, err := c.Send(ctx, "org.thehoster.forskapd.Login", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m Login_methods) Upgrade(ctx context.Context, c *varlink.Connection, host_in_ string, token_in_ string) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Host  string `json:"host"`
		Token string `json:"token"`
	}
	in.Host = host_in_
	in.Token = token_in_
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.Login", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type Logout_methods struct{}

func Logout() Logout_methods { return Logout_methods{} }

func (m Logout_methods) Call(ctx context.Context, c *varlink.Connection) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m Logout_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (uint64, error), error) {
	receive, err := c.Send(ctx, "org.thehoster.forskapd.Logout", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m Logout_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.Logout", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type WhoAmI_methods struct{}

func WhoAmI() WhoAmI_methods { return WhoAmI_methods{} }

func (m WhoAmI_methods) Call(ctx context.Context, c *varlink.Connection) (host_out_ string, user_id_out_ int64, token_expires_at_out_ *int64, token_rotates_out_ bool, err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	host_out_, user_id_out_, token_expires_at_out_, token_rotates_out_, _, err_ = receive(ctx)
	return
}

func (m WhoAmI_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (string, int64, *int64, bool, uint64, error), error) {
	receive, err := c.Send(ctx, "org.thehoster.forskapd.WhoAmI", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (host_out_ string, user_id_out_ int64, token_expires_at_out_ *int64, token_rotates_out_ bool, flags uint64, err error) {
		var out struct {
			Host             string `json:"host"`
			User_id          int64  `json:"user_id"`
			Token_expires_at *int64 `json:"token_expires_at,omitempty"`
			Token_rotates    bool   `json:"token_rotates"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		host_out_ = out.Host
		user_id_out_ = out.User_id
		token_expires_at_out_ = out.Token_expires_at
		token_rotates_out_ = out.Token_rotates
		return
	}, nil
}

func (m WhoAmI_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (host_out_ string, user_id_out_ int64, token_expires_at_out_ *int64, token_rotates_out_ bool, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "org.thehoster.forskapd.WhoAmI", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (host_out_ string, user_id_out_ int64, token_expires_at_out_ *int64, token_rotates_out_ bool, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Host             string `json:"host"`
			User_id          int64  `json:"user_id"`
			Token_expires_at *int64 `json:"token_expires_at,omitempty"`
			Token_rotates    bool   `json:"token_rotates"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		host_out_ = out.Host
		user_id_out_ = out.User_id
		token_expires_at_out_ = out.Token_expires_at
		token_rotates_out_ = out.Token_rotates
		return
	}, nil
}

// Generated service interface with all methods

type orgthehosterforskapdInterface interface {
	GetAssignedIssues(ctx context.Context, c VarlinkCall, groups_ *[]string) error
	GetAssignedMergeRequests(ctx context.Context, c VarlinkCall, groups_ *[]string) error
	Search(ctx context.Context, c VarlinkCall, query_ string, kinds_ *[]string, limit_ *int64) error
	PostTime(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind, duration_ string, summary_ *string) error
	Close(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind) error
	AssignSelf(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind) error
	UnassignSelf(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind) error
	RecordOpen(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind) error
	RecordEpicOpen(ctx context.Context, c VarlinkCall, group_id_ int64, iid_ int64) error
	ClearCache(ctx context.Context, c VarlinkCall, scope_ *[]string) error
	GetHistory(ctx context.Context, c VarlinkCall, days_ *int64) error
	GetActivity(ctx context.Context, c VarlinkCall, days_ *int64) error
	GetFailures(ctx context.Context, c VarlinkCall) error
	RetryFailure(ctx context.Context, c VarlinkCall, id_ int64) error
	DismissFailure(ctx context.Context, c VarlinkCall, id_ int64) error
	ClearFailures(ctx context.Context, c VarlinkCall) error
	GetSyncJobs(ctx context.Context, c VarlinkCall) error
	Login(ctx context.Context, c VarlinkCall, host_ string, token_ string) error
	Logout(ctx context.Context, c VarlinkCall) error
	WhoAmI(ctx context.Context, c VarlinkCall) error
}

// Generated service object with all methods

type VarlinkCall struct{ varlink.Call }

// Generated reply methods for all varlink errors

func (c *VarlinkCall) ReplyGitlabError(ctx context.Context, message_ string) error {
	var out GitlabError
	out.Message = message_
	return c.ReplyError(ctx, "org.thehoster.forskapd.GitlabError", &out)
}

func (c *VarlinkCall) ReplyNotAuthenticated(ctx context.Context, reason_ *NotAuthReason, detail_ *string) error {
	var out NotAuthenticated
	out.Reason = reason_
	out.Detail = detail_
	return c.ReplyError(ctx, "org.thehoster.forskapd.NotAuthenticated", &out)
}

// Generated reply methods for all varlink methods

func (c *VarlinkCall) ReplyGetAssignedIssues(ctx context.Context, issues_ []Issue) error {
	var out struct {
		Issues []Issue `json:"issues"`
	}
	out.Issues = []Issue(issues_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyGetAssignedMergeRequests(ctx context.Context, merge_requests_ []MergeRequest) error {
	var out struct {
		Merge_requests []MergeRequest `json:"merge_requests"`
	}
	out.Merge_requests = []MergeRequest(merge_requests_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplySearch(ctx context.Context, issues_ []Issue, merge_requests_ []MergeRequest, projects_ []Project, groups_ []Group, epics_ []Epic) error {
	var out struct {
		Issues         []Issue        `json:"issues"`
		Merge_requests []MergeRequest `json:"merge_requests"`
		Projects       []Project      `json:"projects"`
		Groups         []Group        `json:"groups"`
		Epics          []Epic         `json:"epics"`
	}
	out.Issues = []Issue(issues_)
	out.Merge_requests = []MergeRequest(merge_requests_)
	out.Projects = []Project(projects_)
	out.Groups = []Group(groups_)
	out.Epics = []Epic(epics_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyPostTime(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyClose(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyAssignSelf(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyUnassignSelf(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyRecordOpen(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyRecordEpicOpen(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyClearCache(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyGetHistory(ctx context.Context, events_ []HistoryEvent) error {
	var out struct {
		Events []HistoryEvent `json:"events"`
	}
	out.Events = []HistoryEvent(events_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyGetActivity(ctx context.Context, events_ []ActivityEvent) error {
	var out struct {
		Events []ActivityEvent `json:"events"`
	}
	out.Events = []ActivityEvent(events_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyGetFailures(ctx context.Context, failures_ []FailedTask) error {
	var out struct {
		Failures []FailedTask `json:"failures"`
	}
	out.Failures = []FailedTask(failures_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyRetryFailure(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyDismissFailure(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyClearFailures(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyGetSyncJobs(ctx context.Context, jobs_ []SyncJob, paused_until_ *int64) error {
	var out struct {
		Jobs         []SyncJob `json:"jobs"`
		Paused_until *int64    `json:"paused_until,omitempty"`
	}
	out.Jobs = []SyncJob(jobs_)
	out.Paused_until = paused_until_
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyLogin(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyLogout(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyWhoAmI(ctx context.Context, host_ string, user_id_ int64, token_expires_at_ *int64, token_rotates_ bool) error {
	var out struct {
		Host             string `json:"host"`
		User_id          int64  `json:"user_id"`
		Token_expires_at *int64 `json:"token_expires_at,omitempty"`
		Token_rotates    bool   `json:"token_rotates"`
	}
	out.Host = host_
	out.User_id = user_id_
	out.Token_expires_at = token_expires_at_
	out.Token_rotates = token_rotates_
	return c.Reply(ctx, &out)
}

// Generated dummy implementations for all varlink methods

func (s *VarlinkInterface) GetAssignedIssues(ctx context.Context, c VarlinkCall, groups_ *[]string) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.GetAssignedIssues")
}

func (s *VarlinkInterface) GetAssignedMergeRequests(ctx context.Context, c VarlinkCall, groups_ *[]string) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.GetAssignedMergeRequests")
}

func (s *VarlinkInterface) Search(ctx context.Context, c VarlinkCall, query_ string, kinds_ *[]string, limit_ *int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.Search")
}

func (s *VarlinkInterface) PostTime(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind, duration_ string, summary_ *string) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.PostTime")
}

func (s *VarlinkInterface) Close(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.Close")
}

func (s *VarlinkInterface) AssignSelf(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.AssignSelf")
}

func (s *VarlinkInterface) UnassignSelf(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.UnassignSelf")
}

func (s *VarlinkInterface) RecordOpen(ctx context.Context, c VarlinkCall, project_id_ int64, iid_ int64, kind_ IssuableKind) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.RecordOpen")
}

func (s *VarlinkInterface) RecordEpicOpen(ctx context.Context, c VarlinkCall, group_id_ int64, iid_ int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.RecordEpicOpen")
}

func (s *VarlinkInterface) ClearCache(ctx context.Context, c VarlinkCall, scope_ *[]string) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.ClearCache")
}

func (s *VarlinkInterface) GetHistory(ctx context.Context, c VarlinkCall, days_ *int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.GetHistory")
}

func (s *VarlinkInterface) GetActivity(ctx context.Context, c VarlinkCall, days_ *int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.GetActivity")
}

func (s *VarlinkInterface) GetFailures(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.GetFailures")
}

func (s *VarlinkInterface) RetryFailure(ctx context.Context, c VarlinkCall, id_ int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.RetryFailure")
}

func (s *VarlinkInterface) DismissFailure(ctx context.Context, c VarlinkCall, id_ int64) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.DismissFailure")
}

func (s *VarlinkInterface) ClearFailures(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.ClearFailures")
}

func (s *VarlinkInterface) GetSyncJobs(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.GetSyncJobs")
}

func (s *VarlinkInterface) Login(ctx context.Context, c VarlinkCall, host_ string, token_ string) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.Login")
}

func (s *VarlinkInterface) Logout(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.Logout")
}

func (s *VarlinkInterface) WhoAmI(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "org.thehoster.forskapd.WhoAmI")
}

// Generated method call dispatcher

func (s *VarlinkInterface) VarlinkDispatch(ctx context.Context, call varlink.Call, methodname string) error {
	switch methodname {
	case "GetAssignedIssues":
		var in struct {
			Groups *[]string `json:"groups,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.GetAssignedIssues(ctx, VarlinkCall{call}, in.Groups)

	case "GetAssignedMergeRequests":
		var in struct {
			Groups *[]string `json:"groups,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.GetAssignedMergeRequests(ctx, VarlinkCall{call}, in.Groups)

	case "Search":
		var in struct {
			Query string    `json:"query"`
			Kinds *[]string `json:"kinds,omitempty"`
			Limit *int64    `json:"limit,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.Search(ctx, VarlinkCall{call}, in.Query, in.Kinds, in.Limit)

	case "PostTime":
		var in struct {
			Project_id int64        `json:"project_id"`
			Iid        int64        `json:"iid"`
			Kind       IssuableKind `json:"kind"`
			Duration   string       `json:"duration"`
			Summary    *string      `json:"summary,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.PostTime(ctx, VarlinkCall{call}, in.Project_id, in.Iid, in.Kind, in.Duration, in.Summary)

	case "Close":
		var in struct {
			Project_id int64        `json:"project_id"`
			Iid        int64        `json:"iid"`
			Kind       IssuableKind `json:"kind"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.Close(ctx, VarlinkCall{call}, in.Project_id, in.Iid, in.Kind)

	case "AssignSelf":
		var in struct {
			Project_id int64        `json:"project_id"`
			Iid        int64        `json:"iid"`
			Kind       IssuableKind `json:"kind"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.AssignSelf(ctx, VarlinkCall{call}, in.Project_id, in.Iid, in.Kind)

	case "UnassignSelf":
		var in struct {
			Project_id int64        `json:"project_id"`
			Iid        int64        `json:"iid"`
			Kind       IssuableKind `json:"kind"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.UnassignSelf(ctx, VarlinkCall{call}, in.Project_id, in.Iid, in.Kind)

	case "RecordOpen":
		var in struct {
			Project_id int64        `json:"project_id"`
			Iid        int64        `json:"iid"`
			Kind       IssuableKind `json:"kind"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.RecordOpen(ctx, VarlinkCall{call}, in.Project_id, in.Iid, in.Kind)

	case "RecordEpicOpen":
		var in struct {
			Group_id int64 `json:"group_id"`
			Iid      int64 `json:"iid"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.RecordEpicOpen(ctx, VarlinkCall{call}, in.Group_id, in.Iid)

	case "ClearCache":
		var in struct {
			Scope *[]string `json:"scope,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.ClearCache(ctx, VarlinkCall{call}, in.Scope)

	case "GetHistory":
		var in struct {
			Days *int64 `json:"days,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.GetHistory(ctx, VarlinkCall{call}, in.Days)

	case "GetActivity":
		var in struct {
			Days *int64 `json:"days,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.GetActivity(ctx, VarlinkCall{call}, in.Days)

	case "GetFailures":
		return s.orgthehosterforskapdInterface.GetFailures(ctx, VarlinkCall{call})

	case "RetryFailure":
		var in struct {
			Id int64 `json:"id"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.RetryFailure(ctx, VarlinkCall{call}, in.Id)

	case "DismissFailure":
		var in struct {
			Id int64 `json:"id"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.DismissFailure(ctx, VarlinkCall{call}, in.Id)

	case "ClearFailures":
		return s.orgthehosterforskapdInterface.ClearFailures(ctx, VarlinkCall{call})

	case "GetSyncJobs":
		return s.orgthehosterforskapdInterface.GetSyncJobs(ctx, VarlinkCall{call})

	case "Login":
		var in struct {
			Host  string `json:"host"`
			Token string `json:"token"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.orgthehosterforskapdInterface.Login(ctx, VarlinkCall{call}, in.Host, in.Token)

	case "Logout":
		return s.orgthehosterforskapdInterface.Logout(ctx, VarlinkCall{call})

	case "WhoAmI":
		return s.orgthehosterforskapdInterface.WhoAmI(ctx, VarlinkCall{call})

	default:
		return call.ReplyMethodNotFound(ctx, methodname)
	}
}

// Generated varlink interface name

func (s *VarlinkInterface) VarlinkGetName() string {
	return `org.thehoster.forskapd`
}

// Generated varlink interface description

func (s *VarlinkInterface) VarlinkGetDescription() string {
	return `interface org.thehoster.forskapd

type Issue (
  id: int,
  iid: int,
  project_id: int,
  title: string,
  web_url: string,
  state: string,
  parent: string,
  total_time: string,
  graph_status: string,
  open_count: int,
  project_avatar: string
)

type IssuableKind (issue, merge_request)

type HistoryEvent (
  timestamp: int,
  source: string,
  kind: IssuableKind,
  project_id: int,
  iid: int,
  title: string,
  web_url: string,
  duration: string,
  summary: string
)

type ActivityEvent (
  timestamp: int,
  action: string,
  target_type: string,
  target_iid: ?int,
  target_title: ?string,
  project_id: int,
  project_path: ?string,
  web_url: ?string,
  ref: ?string,
  commit_count: ?int,
  commit_title: ?string,
  description: ?string
)

type FailedTask (
  id: int,
  op: string,
  kind: IssuableKind,
  project_id: int,
  iid: int,
  detail: string,
  error: string,
  queued_at: int,
  failed_at: int
)

type MergeRequest (
  id: int,
  iid: int,
  project_id: int,
  title: string,
  web_url: string,
  state: string,
  assignees: []string,
  open_count: int,
  project_avatar: string
)

type Project (
  id: int,
  name: string,
  path: string,
  web_url: string,
  avatar: string
)

type Group (
  id: int,
  name: string,
  path: string,
  web_url: string
)

type SyncJobStatus (running, demanded, due, waiting, backing_off)

type SyncJob (
  key: string,
  status: SyncJobStatus,
  last_ok: ?int,
  next_due: ?int,
  running_since: ?int,
  failures: int,
  last_error: ?string
)

type Epic (
  id: int,
  iid: int,
  group_id: int,
  title: string,
  web_url: string,
  state: string,
  open_count: int
)

error GitlabError (message: string)

type NotAuthReason (no_credentials, keychain_error, unreachable, token_rejected, logged_out)

error NotAuthenticated (reason: ?NotAuthReason, detail: ?string)

method GetAssignedIssues(groups: ?[]string) -> (issues: []Issue)

method GetAssignedMergeRequests(groups: ?[]string) -> (merge_requests: []MergeRequest)

method Search(query: string, kinds: ?[]string, limit: ?int) -> (issues: []Issue, merge_requests: []MergeRequest, projects: []Project, groups: []Group, epics: []Epic)

method PostTime(project_id: int, iid: int, kind: IssuableKind, duration: string, summary: ?string) -> ()

method Close(project_id: int, iid: int, kind: IssuableKind) -> ()

method AssignSelf(project_id: int, iid: int, kind: IssuableKind) -> ()

method UnassignSelf(project_id: int, iid: int, kind: IssuableKind) -> ()

method RecordOpen(project_id: int, iid: int, kind: IssuableKind) -> ()

method RecordEpicOpen(group_id: int, iid: int) -> ()

method ClearCache(scope: ?[]string) -> ()

method GetHistory(days: ?int) -> (events: []HistoryEvent)

method GetActivity(days: ?int) -> (events: []ActivityEvent)

method GetFailures() -> (failures: []FailedTask)

method RetryFailure(id: int) -> ()

method DismissFailure(id: int) -> ()

method ClearFailures() -> ()

method GetSyncJobs() -> (jobs: []SyncJob, paused_until: ?int)

method Login(host: string, token: string) -> ()

method Logout() -> ()

method WhoAmI() -> (host: string, user_id: int, token_expires_at: ?int, token_rotates: bool)
`
}

// Generated service interface

type VarlinkInterface struct {
	orgthehosterforskapdInterface
}

func VarlinkNew(m orgthehosterforskapdInterface) *VarlinkInterface {
	return &VarlinkInterface{m}
}
