// Code generated by genversion.go from forskap-api/Cargo.toml; DO NOT EDIT.

package orgthehosterforskapd

// APIVersion is the version of the org.thehoster.forskapd interface this
// binding was generated from: the forskap-api crate's. Compare a daemon's with
// Status.Compatible.
const APIVersion = "1.3.0"
