[package]
name = "forskap-api"
version = "1.2.0"
edition.workspace = true
license = "MIT OR Apache-2.0"

[build-dependencies]
quote.workspace = true
syn.workspace = true
varlink_generator.workspace = true
varlink_parser.workspace = true

[dev-dependencies]
syn.workspace = true
varlink_parser.workspace = true

[dependencies]
async-trait.workspace = true
dirs.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
varlink.workspace = true
